#!/bin/bash

# Copy keys to system and detect device
if [ -d /app/adbkeys ]; then
  echo "Copy device keys .."
  cp /app/adbkeys/* /root/.android/
  adb devices
fi

# Setup Gradle link
if [ ! -d /app/.gradle ]; then
  mkdir -p /app/.gradle
fi
ln -s /app/.gradle /root/.gradle

/usr/bin/tns "$@"
